DEV-44 Added symfony 6 support
marfatech/swagger-resolver-bundle pull request #3
Opened 2022-04-21 16:19 UTC by iamskey

2022-04-22 08:43 UTC, iamskey commented
поддержка старых версий убрана из-за типизации в новой версии options-resolver bundle

2022-04-22 15:22 UTC, revilon1991 commented on composer.json
> -        "symfony/yaml":                 "~3.4||~4.0||~5.0"
мб 5ую оставим? мне нужны будут фичи с этого бандла на проекте с 5ой версий симфони.

2022-04-22 15:23 UTC, revilon1991 commented on composer.json
> -        "symfony/yaml":                 "~3.4||~4.0||~5.0"
или как вариант вести новую мажерную версию, но это затратно

2022-04-23 12:02 UTC, iamskey commented on composer.json
> -        "symfony/yaml":                 "~3.4||~4.0||~5.0"
вернул 4-ку и 5-ку

2022-05-16 13:58 UTC, revilon1991 requested changes

2022-05-16 13:58 UTC, revilon1991 commented on Tests/ResolverTest.php
> + * (c) Viktor Linkin <adrenalinkin@gmail.com>
Для новых файлов наше копирайты.
```suggestion
 * (c) MarfaTech <https://marfa-tech.com>
```

2022-06-21 13:03 UTC, revilon1991 requested changes
тесты на ГА не проходят

2022-07-01 13:33 UTC, revilon1991 approved these changes

2022-07-01 13:34 UTC, merged